[metadata]
name = area_classification
description = Brief overview of your project.
version = 0.0.1
author = ONS
platforms = win32
classifiers =
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
packages =
    area_classification
python_requires = >=3.9
zip_safe = no
install_requires =
    pyyaml
    requests
    pandas
    bs4
    pyarrow
    clustergram
    scikit-learn
    matplotlib

[options.extras_require]
dev =
    coverage
    detect-secrets == 1.0.3
    myst-parser
    pre-commit
    pytest
    detect-secrets
    python-dotenv
    Sphinx
    toml
