[metadata]
name = area_classification
description = Brief overview of your project.
version = 0.0.1
author = ONS
platforms = win32
classifiers =
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
packages =
    area_classification
    area_classification.clustering
    area_classification.downloading_data
    area_classification.post_processing
    area_classification.pre_processing
    area_classification.utilities
include_package_data = True
python_requires = >=3.9
zip_safe = no
install_requires =
    pyyaml
    requests
    pandas
    beautifulsoup4
    pyarrow
    clustergram
    scikit-learn
    matplotlib
    openpyxl
    xlrd
    xlwt

[options.extras_require]
dev =
    coverage
    detect-secrets == 1.0.3
    myst-parser
    pre-commit
    pytest
    detect-secrets
    python-dotenv
    Sphinx
    toml

[options.packages.find]
where = area_classification
