# Config file for the Area Classification project

working_directory : ~/Area_Classification

#File paths which will need amending



#File paths which should not need amending

#The LAD and select codes lookup tables should be saved in the lookups folder
LAD_lookup_file_path: 'data/lookups/Local_Authority_Districts_(December_2022)_Names_and_Codes_UK.csv'
select_variables_lookup: 'area_classification/data/lookups/UK_selected_codes_lookup.csv'
#The manually downloaded Scot tables (and those for EW and NI) should be saved in inputs
scot_input_folder: 'data/inputs/scot_downloads/'

qa_folder_path: './data/QA/'

ni_pop_density_filepath: 'D:/Repos/Area_Classification_data/census-2021-ms-a14-LGD.xlsx' 
input_data_directory: 'data/inputs/'

number_of_clusters: 8
number_of_times_k_means_initialised: 10 # 1000 for real run
#output_directory: 'data/output_data/'

plot_directory: 'data/plots/'
random_seed: 42

select_variables_lookup: "data/lookups/UK_selected_codes_lookup.csv"

england_wales_disability_file: "ew_disability_age_group.csv"
ni_disability_file: "ni_disability_age_group.csv"
scotland_disability_file: "scot_disability_age_group.csv"

england_wales_disability_input: "ew_downloads/disabilitycensus2021.xlsx"
ni_disability_input: "ni_downloads/census-2021-ms-d02.xlsx"
scotland_disability_input: "scot_downloads/UV303a.csv"

ew_file_pattern: "ts???*.csv"
ew_join_column_name: "LTLA"
ew_excluded_form_code: ["ts006"]

ni_file_pattern: "ni???.csv"
ni_join_column_name: "LGD"
ni_excluded_form_code: ["population_density"]

scot_join_column_name: "CA19"
scot_excluded_form_code: ["population_density"]

# These tables dont have OA data for England and Wales
england_and_wales_table_codes_to_remove : [
        "ts007",
        "ts009",
        "ts010",
        "ts012",
        "ts013",
        "ts071",
        "ts072",
        "ts073",
        "ts074",
        "ts022",
        "ts024",
        "ts028",
        "ts031",
        "ts076",
        "ts060",
        "ts064",
        "ts047",
        "ts048",
        "ts079",
        "ts070",
        "ts077",
        "ts078",
        "ts037asp",
        "ts038asp",
        "ts039asp"
    ]
