# Config file for the Area Classification project

working_directory : ~/Area_Classification

#*****FILE PATHS AND CONFIGURATIONS WHICH MAY NEED AMENDING*****
#The LAD lookup tables should be saved in the lookups folder
LAD_lookup_file_path: './data/lookups/Local_Authority_Districts_(December_2022)_Names_and_Codes_in_the_United_Kingdom.csv'

#Varaibles chosen
drop_columns: True # Set to true to drop the variables specified below in 'variables to drop' 
                   # or set to false to include 60 varabiles.
variables_to_drop  : [
        "v07", # Families with no children
        "v09", # Europe: United Kingdom
        "v11", # Africa
        "v20", # Bangladeshi (variable not available for NI at this level of geography)
        "v23", # Pakistani
        "v32", # Other religion
        "v40", # Under occupation
        "v41", # Overcrowding    
        "v42", # Social rented
        "v60"  # Level 4 qualifications or above 
        ]

# Data to use in clustering
pre_clustering_data: './data/inputs/pre_clustering_data.csv'

#Clustering config
number_of_clusters: 6
number_of_clusters_supergroup: 6
number_of_clusters_group: 6
number_of_clusters_subgroup: 6
number_of_times_k_means_initialised: 1000 #for real run
random_seed: 42

#*****FILE PATHS AND CONFIGURATIONS WHICH SHOULD NOT NEED AMENDING*****
# Variables lookup
select_variables_lookup: './data/lookups/UK_selected_codes_lookup.csv'

#General file paths
input_data_directory: './data/inputs/'
qa_folder_path: './data/QA/'
output_directory: './data/output_data/'
plot_directory: './data/plots/'

#The manually downloaded Scot tables (and those for EW and NI) should be saved in inputs
scot_input_folder: './data/inputs/scot_downloads/'

# Manually downloaded population density table file path
ni_pop_density_filepath: './data/inputs/ni_downloads/census-2021-ms-a14-LGD.xlsx' 

#Downloading data config
ew_file_pattern: 'ts???*.csv'
ew_join_column_name: 'LTLA'
ew_excluded_form_code: ["ts006"]

ni_file_pattern: 'ni*.csv'
ni_join_column_name: 'LGD'
ni_excluded_form_code: ["population_density"]

scot_join_column_name: 'CA19'
scot_excluded_form_code: ["population_density"]

#SIR config
england_wales_disability_file: 'ew_disability_age_group.csv'
ni_disability_file: 'ni_disability_age_group.csv'
scotland_disability_file: 'scot_disability_age_group.csv'

england_wales_disability_input: 'ew_downloads/disabilitycensus2021.xlsx'
ni_disability_input: 'ni_downloads/census-2021-ms-d02.xlsx'
scotland_disability_input: 'scot_downloads/UV303a.csv'

#Post clustering table restructure
keep_column: 'LAD_code' #Name of the column to keep as-is.
split_column: 'subsubcluster' # Name of the column to split into separate characters.

# These tables dont have OA data for England and Wales
england_and_wales_table_codes_to_remove : [
        "ts007",
        "ts009",
        "ts010",
        "ts012",
        "ts013",
        "ts071",
        "ts072",
        "ts073",
        "ts074",
        "ts022",
        "ts024",
        "ts028",
        "ts031",
        "ts076",
        "ts060",
        "ts064",
        "ts047",
        "ts048",
        "ts079",
        "ts070",
        "ts077",
        "ts078",
        "ts037asp",
        "ts038asp",
        "ts039asp"
    ]
