# Instructions on how to fill this out can be found: README.md
# There is also an example config file included in this package: config_example.yaml

save_info:
  save_location: 'D:\Repos\Area_Classification\data\output_data'
  file_save_name:  'Area-classification-2021-2022'

cover:
  include_cover: True
  sheet_label: 'Cover'
  cover_title: 'Local Authority District (LAD) Area Classifications 2021/22' 
  introductory_information: ['Area classification for the Local Authority District level of geography.',
                            '']
  about_these_data: [
        [{"bold": True}, "Publication dates"], 
        "The data tables in this spreadsheet were originally published at 7:00am 01 February 2026.",
        "This publication is released once every 10 years (associated with census) The next publication is to be confirmed.'",
        [{"bold": True}, "Coverage"], 
        "This classification covers the Local Authority District level for the UK.",
        [{"bold": True}, "Source"],
        "Data was sourced from the 2021 Census for lower-tier local authorities (LTLAs) in England and Wales and Local Government Districts (LGD) in Northern Ireland, and from the 2022 Census data for Council Areas (CA) in Scotland.",
        [{"bold": True}, "Methodology notes"],
        "Information on methodology can be found on the ONS digital GitHub and Area Classification pages on the ONS website",
        [{"bold": True}, "Website"], 
        "https://www.ons.gov.uk/methodology/geography/geographicalproducts/areaclassifications/2021residentialbasedareaclassifications",
    ]
  contact: ['Geospatial Team, ONS',
           'Email: [Geospatial@ons.gov.uk](mailto: Geospatial@ons.gov.uk)']

contents:
  include_contents: False 
  sheet_label: 

notes:
  include_notes: True 
  sheet_label: 'Notes'
  notes_title: 'Notes'
  notes_instructions: 
  notes_table: {
      'Note reference': [
        'note 1', 
        'note 2'
        ],
      'Note text': [
        '[note 1] is a note about ABC', 
        '[note 2] us a note about XYZ'
        ]
  }

datasets:
  - table_id: 'Cluster_Codes_names_and_counts'
    sheet_label: 'Cluster codes, names and count'
    table_title: 'Cluster codes, names and count'
    #table_subtitle: 'Cluster codes, names and the counts of each code in the clusters for the 2021/22 local authority district area classification'
    table_subtitle:
    instructions: ""
    table_source_file: 'D:/Repos/Area_Classification/data/output_data/cluster_totals.csv'
    sheet_name: 

  - table_id: '2021/22_Local_Authorities_by_Clusters'
    sheet_label: 'Local Authorities by Clusters' 
    table_title: 'Local Authorities by Clusters'
    table_subtitle:
    #table_subtitle: 'Local Authority Districts grouped into supergroups, groups and subgroup clusters'
    instructions: ""
    table_source_file: 'D:/Repos/Area_Classification/data/output_data/cluster_names.csv'
    sheet_name: null